name: Explosion Bot Please

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  explosion-bot-please:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/explosion-bot-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          users: "ines, honnibal, svlandeg, adrianeboyd, justindujardin, tiangolo"
